using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.Collections;
using System.Net.Mail;

namespace JSHL
{
    public partial class hrdash : System.Web.UI.Page
    {
        
        SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["IndustrialTrainingConnectionString"].ConnectionString);
        protected void Page_Load(object sender, EventArgs e)
        {
            Page.Title = "DashBoard";
            if (Session["Login"] == null)
            {
                var page = HttpContext.Current.CurrentHandler as Page;
                ScriptManager.RegisterStartupScript(page, page.GetType(), "alert", "alert('Session is Over/Logged Out');window.location ='login.aspx';", true);

            }
            else if (Session["AppNo"] == null)
            {
                var page = HttpContext.Current.CurrentHandler as Page;
                ScriptManager.RegisterStartupScript(page, page.GetType(), "alert", "alert('Application is not Selected');window.location ='hr.aspx';", true);

            }
            else
            {
                string Application = Session["AppNo"].ToString();
                Label1.Text = Application;
            }
        }

        protected void assign_Click(object sender, EventArgs e)
        {
            string dir = Request.Url.GetLeftPart(UriPartial.Authority) + Request.ApplicationPath;

            conn.Open();
            string qr = "update hrapproved set PlantCode = '" + plantcode.SelectedItem.Value + "',Department = '" + department.SelectedItem.Value + "' where ApplicationNumber = '" + Session["AppNo"] + "'";
            SqlCommand cmd = new SqlCommand(qr, conn);
            cmd.ExecuteNonQuery();
            string qr1 = "update appstatus set Status = 'HR APPROVED' where ApplicationNumber = '" + Session["AppNo"] + "'";
            SqlCommand cmd1 = new SqlCommand(qr1, conn);
            cmd1.ExecuteNonQuery();
            string qr3 = "select Email from adminlog where Department = '" + department.SelectedItem.Value + "' and PlantCode = '" + plantcode.SelectedItem.Value + "'";
            SqlCommand cmd3 = new SqlCommand(qr3, conn);
            string deptem = (String)cmd3.ExecuteScalar();
            cmd.Dispose();
            cmd1.Dispose();
            string image = "";
            string qr4 = "SELECT [Document] FROM DocumentUpload WHERE (ApplicationNumber = @app)";
            SqlCommand cmd4 = new SqlCommand(qr4, conn);
            cmd4.Parameters.AddWithValue("@app", Session["AppNo"]);
            SqlDataReader pre;
            pre = cmd4.ExecuteReader();
            while (pre.Read())
            {
                image = pre.GetValue(0).ToString();
            }
            pre.Close();
            cmd4.Dispose();
            conn.Close();

            MailMessage mail = new MailMessage();
            mail.Subject = "Industrial Training JSHL (Department Mail)";
            mail.From = new MailAddress("Mailid");
            mail.To.Add("yashjain.2016@vitstudent.ac.in");
            mail.Body = "A New Application for Industrial Training is Allotted to Your Department by HR Department.<br>Application Number is " + Session["AppNo"] + "<br>To Process the application <a href=\"" + dir + "login.aspx\"><u>Click Here</u></a><br><br>This is an Autogenerated Mail,Please don't Reply.<br><br>";
            mail.IsBodyHtml = true;

            SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
            smtp.EnableSsl = true;
            smtp.Credentials = new System.Net.NetworkCredential("Mailid", "Password");

            MailMessage mail1 = new MailMessage();
            Attachment doc = new Attachment(Server.MapPath(image));

            mail1.Subject = "Industrial Training JSHL (" + Session["AppNo"] + ") (For Gate Pass)";
            mail1.From = new MailAddress("Mailid");
            mail1.To.Add("yashjain.2016@vitstudent.ac.in");
            mail1.Body = "A New Application with Application Number: " + Session["AppNo"] + " is Approved by HR.<br>Please Generate Gate Pass.<br>To Generate Gate Pass <a href=\"" + dir +"gatepassapp.aspx?ApplicationNumber=" + Session["AppNo"] + "\"><u>Click Here</u></a><br>";
            mail1.IsBodyHtml = true;
            mail1.Attachments.Add(doc);
            SmtpClient smtp1 = new SmtpClient("smtp.gmail.com", 587);
            smtp1.EnableSsl = true;
            smtp1.Credentials = new System.Net.NetworkCredential("Mailid", "Password");

            try
            {
                smtp1.Send(mail1);
            }
            catch (Exception ex)
            {
                Console.WriteLine("{0} Exception caught.", ex);
            }

            try
            {
                smtp.Send(mail);
            }
            catch (Exception ex)
            {
                Console.WriteLine("{0} Exception caught.", ex);
            }

            var page = HttpContext.Current.CurrentHandler as Page;
            ScriptManager.RegisterStartupScript(page, page.GetType(), "alert", "alert('Application Assigned Successfully ');window.location ='hr.aspx';", true);

        }
    }
}
